//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int feedback_id { get; set; }
        public int driver_id { get; set; }
        public Nullable<int> points { get; set; }
        public System.DateTime created { get; set; }
    }
}
